### ISSUE TITLE
Bug: Wi-Fi Signal Icon

### ISSUE THREAD

**Issue by 8227846265** [PixelExperience-Devices/device_xiaomi_beryllium#12]
**Bug Description:**

- VPN is installed
- VPN Settings:
A. Always-on VPN = Enabled
B. Block connections without VPN = Enabled

**The right status bar changes from this**
![image](https://user-images.githubusercontent.com/66582769/98322028-72fb1800-2021-11eb-92a3-a54f3ef6adc0.png)

**To this**
![image](https://user-images.githubusercontent.com/66582769/98321735-c882f500-2020-11eb-8bf7-eb9de1716b43.png)

Sometimes, it even affects **SIM 1 Signal Bar Icon** when you **turn off the Wi-Fi**. The following will disappear Key Icon (VPN) and **SIM 1 Signal Bar Icon** will become a dot.

**Comment by lakgarg** [comment]
Status Bar padding has been adjusted👍
