### ISSUE TITLE
Screen blinks always

### ISSUE THREAD

**Issue by onarion** [PixelExperience-Devices/device_xiaomi_beryllium#5]
Sorry for report again! :\

So, screen blinks whenever I switch apps.

**Comment by aecarvalho** [comment]
Even I've noticed slight screen blinks in certain apps like Mx Player Pro for example when a movie is paused, or on Chrome at times, it's a very light flicker - a slight variation in screen brightness.

**Comment by lakgarg** [comment]
Does this issue persist even now?
